# Generated by Django 4.0.4 on 2022-05-09 21:17

from django.db import migrations


def combine_info(apps, schema_editor):
    Book = apps.get_model('books', 'Book')
    for book in Book.objects.all():
        book.title = f'{book.title}'
        book.author = f'{book.author}'
        book.released_at = f'{book.released_at}'
        book.description = f'{book.description}'
        book.save()


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(combine_info),
    ]
