# Generated by Django 4.0.4 on 2022-05-09 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_url'),
        ('books', '0004_auto_20220509_1717'),
    ]

    operations = [
    ]
